### ISSUE TITLE
fix/remove private links in readme

### ISSUE THREAD

**Issue by midu** [blueapron/blueapron-events#22]
- [x] circleci: private, we could switch to travis if they don't have a public version
- [x] code climate: I believe they have a public project option
- [x] gemnasium: same

**Comment by midu** [comment]
@prsimp made gemnasium [public](https://gemnasium.com/blueapron/blueapron-events), but it broke the image in the readme

**Comment by prsimp** [comment]
Code Climate: I had to re-add the repo as an "Open Source" repo. I re-added the PR integration.
CircleCI: resolved itself (immediately after I reached out to support).

**Comment by midu** [comment]
fantastic!
